apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathpix-api
  labels:
    app: mathpix-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathpix-api
  template:
    metadata:
      labels:
        app: mathpix-api
    spec:
      containers:
        - name: mathpix-onprem
          envFrom:
            - configMapRef:
                name: mathpix-env
          resources:
            requests:
              cpu: "12"
              memory: 32Gi
            limits:
              nvidia.com/gpu: "1"
          image: REPLACE_ME
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /region-health
              port: 8070
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /region-health
              port: 8070
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8070
