apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: rabbitmq-cluster-pod-disruption-budget
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-cluster