apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/consumer

patches:
  - path: configmap.yaml
  - path: secrets.yaml
  ## Uncomment below if you need to add imagePullSecrets
  # - target:
  #     kind: Deployment
  #     name: scs-consumer
  #   patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: scs-consumer
  #     spec:
  #       template:
  #         spec:
  #           imagePullSecrets:
  #             - name: my-registry-secret
  ## Uncomment below if you need to change the instance type to use
  # multiple GPUs or request more resources like CPU or memory, in
  # addition to changing the configmap.yaml's DEVICE_COUNT variable
  # - target:
  #     kind: Deployment
  #     name: scs-consumer
  #   patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: scs-consumer
  #     spec:
  #       template:
  #         spec:
  #           containers:
  #             - name: scs-consumer
  #               resources:
  #                 requests:
  #                   cpu: "32"
  #                   memory: 300Gi
  #                 limits:
  #                   nvidia.com/gpu: "4"

images:
  - name: external_image
    newName: REPLACE_WITH_REGISTRY_REPO_IMAGE
    newTag: REPLACE_WITH_REGISTRY_REPO_IMAGE_TAG

replicas:
- name: scs-consumer
  count: 1

configMapGenerator:
  - name: scs-conversion-config
    behavior: replace
    files:
      - conversion_options.json
      - ocr_options.json
