apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/consumer

patches:
  - path: configmap.yaml
  - path: secrets.yaml

images:
  - name: external_image
    newName: REPLACE_WITH_REGISTRY_REPO_IMAGE
    newTag: REPLACE_WITH_REGISTRY_REPO_IMAGE_TAG

replicas:
- name: scs-consumer
  count: 1

configMapGenerator:
  - name: scs-conversion-config
    behavior: replace
    files:
      - conversion_options.json
      - ocr_options.json
