apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/publisher

patches:
  - path: configmap.yaml
  - path: secrets.yaml
  # # Uncomment below if you need to add imagePullSecrets
  # - target:
  #     kind: Deployment
  #     name: scs-consumer
  #   patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: scs-consumer
  #     spec:
  #       template:
  #         spec:
  #           imagePullSecrets:
  #             - name: my-registry-secret
images:
  - name: external_image
    newName: REPLACE_WITH_REGISTRY_REPO_IMAGE
    newTag: REPLACE_WITH_REGISTRY_REPO_IMAGE_TAG