apiVersion: batch/v1
kind: Job
metadata:
  name: mathpix-update-credentials
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command:
            - /bin/sh
            - -c
            - |
              until PGPASSWORD=password psql -h postgres -U user -d mathpix -c "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'appkeys');" | grep -q 't'; do
                echo "Waiting for postgres and appkeys table..."
                sleep 2
              done
      containers:
        - name: mathpix-credentials-setup
          image: 426887012336.dkr.ecr.us-east-1.amazonaws.com/mathpix/on-prem-credentials:1.0.0
          imagePullPolicy: Always
          env:
            - name: MATHPIX_OCR_DB
              value: "postgres://user:password@postgres:5432/mathpix"
          volumeMounts:
            - name: credentials-volume
              mountPath: /app/credentials.json
              subPath: credentials.json
      volumes:
        - name: credentials-volume
          configMap:
            name: mathpix-api-credentials
      restartPolicy: Never
  backoffLimit: 4
