apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - update-credentials.yaml

configMapGenerator:
  - name: mathpix-api-credentials
    files:
      - credentials.json

images:
  - name: on-prem-credentials
    newName: 426887012336.dkr.ecr.us-east-1.amazonaws.com/mathpix/on-prem-credentials
    newTag: 1.0.0
