{{- if and (not .Values.postgres.connectionString) .Values.postgres.credentials.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.credentials.configMapName }}
data:
  # Mountable key must exactly match what your Job expects:
  credentials.json: |-
{{ .Files.Get .Values.postgres.credentials.file | indent 4 }}
{{- end }}
