apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-mathpix-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mathpix-ocr.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.global.env }}
  {{ $key }}: "{{ $val }}"
{{- end }}