{{- if not .Values.postgres.connectionString }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-postgres-config
  namespace: mathpix-ocr
data:
  POSTGRES_DB: {{ .Values.postgres.database }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-postgres-pvc
  namespace: mathpix-ocr
spec:
  accessModes: 
  {{ toYaml .Values.postgres.persistence.accessModes | indent 4 }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-postgres
  namespace: mathpix-ocr
spec:
  serviceName: {{ include "mathpix-ocr.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mathpix-ocr.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "mathpix-ocr.fullname" . }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mathpix-ocr.fullname" . }}-postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mathpix-ocr.fullname" . }}-postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "mathpix-ocr.fullname" . }}-postgres-config
                  key: POSTGRES_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "mathpix-ocr.fullname" . }}-postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-postgres
  namespace: mathpix-ocr
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ include "mathpix-ocr.fullname" . }}-postgres
  clusterIP: None

{{- end }}
