apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-rabbitmq-config
  namespace: {{ include "mathpix-ocr.fullname" . }}-mathpix-ocr
data:
  RABBITMQ_DEFAULT_USER: "guest"
  RABBITMQ_DEFAULT_PASS: "guest"
  RABBITMQ_DEFAULT_VHOST: "/"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-rabbitmq
  namespace: {{ include "mathpix-ocr.fullname" . }}-mathpix-ocr
spec:
  serviceName: {{ include "mathpix-ocr.fullname" . }}-rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mathpix-ocr.fullname" . }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ include "mathpix-ocr.fullname" . }}-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          envFrom:
            - configMapRef:
                name: {{ include "mathpix-ocr.fullname" . }}-rabbitmq-config
          volumeMounts:
            - name: {{ include "mathpix-ocr.fullname" . }}-rabbitmq-data
              mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
    - metadata:
        name: {{ include "mathpix-ocr.fullname" . }}-rabbitmq-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-rabbitmq
  namespace: {{ include "mathpix-ocr.fullname" . }}-mathpix-ocr
spec:
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
    - port: 15672
      targetPort: 15672
      name: management
  selector:
    app: {{ include "mathpix-ocr.fullname" . }}-rabbitmq
