apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-redis
  namespace: mathpix-ocr
spec:
  serviceName: {{ include "mathpix-ocr.fullname" . }}-redis
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mathpix-ocr.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "mathpix-ocr.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: {{ include "mathpix-ocr.fullname" . }}-redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: {{ include "mathpix-ocr.fullname" . }}-redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-redis
  namespace: mathpix-ocr
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: {{ include "mathpix-ocr.fullname" . }}-redis
  clusterIP: None
