apiVersion: v1
kind: Service
metadata:
  name: mathpix-ocr-loadbalancer
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mathpix-ocr.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "mathpix-ocr.fullname" . }}-ocr-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
