# Service Account for ecr cred refresh
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-credential-updater
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "mathpix-ocr.labels" . | nindent 4 }}