apiVersion: v1
kind: Service
metadata:
  name: mathpix-ocr-loadbalancer
  namespace: mathpix-ocr
spec:
  selector:
    app: mathpix-ocr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8070
  type: LoadBalancer
