{{- if and (not .Values.postgres.connectionString) .Values.postgres.migration.enabled .Values.postgres.credentials.enabled }}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mathpix-ocr.fullname" . }}-update-credentials
  namespace: {{ include "mathpix-ocr.fullname" . }}-mathpix-ocr
  annotations:
    # run after install/upgrade, but _after_ migrate-schema (weight 1 > weight 0)
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: {{ .Values.postgres.credentials.backoffLimit }}
  template:
    spec:
      initContainers:
        - name: wait-for-appkeys
          image: postgres:{{ .Values.postgres.image.tag }}
          command:
            - /bin/sh
            - -c
            - |
              until PGPASSWORD={{ .Values.postgres.password }} \
                psql -h {{ include "mathpix-ocr.fullname" . }}-postgres \
                -U {{ .Values.postgres.user }} \
                -d {{ .Values.postgres.database }} \
                -c "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name='appkeys');" \
                | grep -q 't'; do
                echo "Waiting for postgres and appkeys table..."
                sleep 2
              done
      containers:
        - name: setup-credentials
          image: {{ .Values.postgres.credentials.image }}
          imagePullPolicy: {{ .Values.postgres.credentials.imagePullPolicy }}
          env:
            - name: MATHPIX_OCR_DB
              value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ include "mathpix-ocr.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
          volumeMounts:
          - name: credentials-volume
            mountPath: /app/credentials.json
            subPath: credentials.json

      volumes:
        - name: credentials-volume
          configMap:
            name: {{ .Values.postgres.credentials.configMapName }}
      restartPolicy: Never

{{- end }}
