apiVersion: v1
kind: ConfigMap
metadata:
  name: scs-consumer-config
data:
  # These should be replaced
  NAME: REPLACE_ME
  JOB_ID: REPLACE_ME

  # Adjustable GPU count should match the GPU count of the node
  DEVICE_COUNT: "1"

  # Adjustable worker counts
  NUM_WORKERS_PER_DEVICE: "2"
  NUM_CONVERSION_WORKERS: "2"
  NUM_FINALIZE_WORKERS: "2"
  NUM_PREPARE_INPUT_WORKERS: "2"

  # Adjustable limitations
  MAX_PDF_PAGES: "5000"
  PDF_PER_PAGE_TIMEOUT: "10"

  # These are the output format configurations
  EXT_LIST: ".lines.json,.lines.mmd.json,.anno_map.json,.document.json"
  CONVERSION_OPTIONS_FILE: "/home/ubuntu/monorepo/ocr-api/mathpix/ocr_service/process_folder/configs/conversion_options.json"
  OCR_OPTIONS_FILE: "/home/ubuntu/monorepo/ocr-api/mathpix/ocr_service/process_folder/configs/ocr_options.json"

  # This option makes all the output files be zipped in an outputs.zip file
  SAVE_OUTPUTS_AS_ZIP: "false"

  # Environment variables that don't need to be changed below
  MATHPIX_ENV: "custom"
